export const ConsequencesTableMockData = {
  data: {
    ssms: [
      {
        consequence: [
          {
            consequence_id: '21079bfa-29d6-50a9-b754-c342a680489b',
            transcript: {
              transcript_id: 'ENST00000619186',
              aa_change: 'R123W',
              is_canonical: false,
              consequence_type: 'missense_variant',
              annotation: {
                hgvsc: 'c.367C>T',
                polyphen_impact: 'probably_damaging',
                polyphen_score: 1,
                sift_impact: 'deleterious',
                sift_score: 0,
                vep_impact: 'MODERATE',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
          {
            consequence_id: '8f36ff72-3d84-5d9c-8121-2777c5b1fc8e',
            transcript: {
              transcript_id: 'ENST00000504290',
              aa_change: 'R150W',
              is_canonical: false,
              consequence_type: 'missense_variant',
              annotation: {
                hgvsc: 'c.448C>T',
                polyphen_impact: 'probably_damaging',
                polyphen_score: 0.998,
                sift_impact: 'deleterious',
                sift_score: 0,
                vep_impact: 'MODERATE',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
          {
            consequence_id: 'ef5b458a-e651-5b00-a13f-04723ca78015',
            transcript: {
              transcript_id: 'ENST00000505014',
              aa_change: null,
              is_canonical: false,
              consequence_type: 'downstream_gene_variant',
              annotation: {
                hgvsc: '',
                polyphen_impact: '',
                polyphen_score: null,
                sift_impact: '',
                sift_score: null,
                vep_impact: 'MODIFIER',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
          {
            consequence_id: '946b0f17-7c36-526b-97ae-852fb522787f',
            transcript: {
              transcript_id: 'ENST00000508793',
              aa_change: null,
              is_canonical: false,
              consequence_type: 'downstream_gene_variant',
              annotation: {
                hgvsc: '',
                polyphen_impact: '',
                polyphen_score: null,
                sift_impact: '',
                sift_score: null,
                vep_impact: 'MODIFIER',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
          {
            consequence_id: 'e790500e-18b0-553c-a65d-481a18ed6792',
            transcript: {
              transcript_id: 'ENST00000635293',
              aa_change: 'R243W',
              is_canonical: false,
              consequence_type: 'missense_variant',
              annotation: {
                hgvsc: 'c.727C>T',
                polyphen_impact: 'probably_damaging',
                polyphen_score: 1,
                sift_impact: 'deleterious',
                sift_score: 0,
                vep_impact: 'MODERATE',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
          {
            consequence_id: '6b2058cb-adec-5461-8411-43e25bbc382b',
            transcript: {
              transcript_id: 'ENST00000610538',
              aa_change: 'R243W',
              is_canonical: false,
              consequence_type: 'missense_variant',
              annotation: {
                hgvsc: 'c.727C>T',
                polyphen_impact: 'probably_damaging',
                polyphen_score: 0.998,
                sift_impact: 'deleterious',
                sift_score: 0,
                vep_impact: 'MODERATE',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
          {
            consequence_id: 'f930aec2-051c-5890-a353-3042744fde67',
            transcript: {
              transcript_id: 'ENST00000503591',
              aa_change: null,
              is_canonical: false,
              consequence_type: 'downstream_gene_variant',
              annotation: {
                hgvsc: '',
                polyphen_impact: '',
                polyphen_score: null,
                sift_impact: '',
                sift_score: null,
                vep_impact: 'MODIFIER',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
          {
            consequence_id: '3e52d1c4-2ef9-5733-9dd2-2365c97f3368',
            transcript: {
              transcript_id: 'ENST00000574684',
              aa_change: null,
              is_canonical: false,
              consequence_type: 'downstream_gene_variant',
              annotation: {
                hgvsc: '',
                polyphen_impact: '',
                polyphen_score: null,
                sift_impact: '',
                sift_score: null,
                vep_impact: 'MODIFIER',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
          {
            consequence_id: 'bc3fdcd6-71d5-5c0a-afaf-fc3c41748cc6',
            transcript: {
              transcript_id: 'ENST00000504937',
              aa_change: 'R150W',
              is_canonical: false,
              consequence_type: 'missense_variant',
              annotation: {
                hgvsc: 'c.448C>T',
                polyphen_impact: 'probably_damaging',
                polyphen_score: 1,
                sift_impact: 'deleterious',
                sift_score: 0,
                vep_impact: 'MODERATE',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
          {
            consequence_id: 'd220941c-9189-5375-afbc-81dacb33cc7b',
            transcript: {
              transcript_id: 'ENST00000618944',
              aa_change: 'R123W',
              is_canonical: false,
              consequence_type: 'missense_variant',
              annotation: {
                hgvsc: 'c.367C>T',
                polyphen_impact: 'probably_damaging',
                polyphen_score: 0.999,
                sift_impact: 'deleterious',
                sift_score: 0,
                vep_impact: 'MODERATE',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
          {
            consequence_id: 'a618c622-8281-5c82-9123-577ebe813fc8',
            transcript: {
              transcript_id: 'ENST00000455263',
              aa_change: 'R282W',
              is_canonical: false,
              consequence_type: 'missense_variant',
              annotation: {
                hgvsc: 'c.844C>T',
                polyphen_impact: 'probably_damaging',
                polyphen_score: 0.998,
                sift_impact: 'deleterious',
                sift_score: 0,
                vep_impact: 'MODERATE',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
          {
            consequence_id: 'feae74fa-99ae-507e-b2d5-606b85e26655',
            transcript: {
              transcript_id: 'ENST00000622645',
              aa_change: 'R243W',
              is_canonical: false,
              consequence_type: 'missense_variant',
              annotation: {
                hgvsc: 'c.727C>T',
                polyphen_impact: 'probably_damaging',
                polyphen_score: 0.999,
                sift_impact: 'deleterious',
                sift_score: 0,
                vep_impact: 'MODERATE',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
          {
            consequence_id: 'c76d9a2d-66ea-52b2-9058-13aa760ed249',
            transcript: {
              transcript_id: 'ENST00000359597',
              aa_change: 'R282W',
              is_canonical: false,
              consequence_type: 'missense_variant',
              annotation: {
                hgvsc: 'c.844C>T',
                polyphen_impact: 'probably_damaging',
                polyphen_score: 0.999,
                sift_impact: 'deleterious',
                sift_score: 0,
                vep_impact: 'MODERATE',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
          {
            consequence_id: '8a5e36f2-1ca2-5766-b865-2511b6e9edde',
            transcript: {
              transcript_id: 'ENST00000610623',
              aa_change: 'R123W',
              is_canonical: false,
              consequence_type: 'missense_variant',
              annotation: {
                hgvsc: 'c.367C>T',
                polyphen_impact: 'probably_damaging',
                polyphen_score: 0.998,
                sift_impact: 'deleterious',
                sift_score: 0,
                vep_impact: 'MODERATE',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
          {
            consequence_id: '6a271391-dae2-5457-837c-ea3780d191de',
            transcript: {
              transcript_id: 'ENST00000445888',
              aa_change: 'R282W',
              is_canonical: false,
              consequence_type: 'missense_variant',
              annotation: {
                hgvsc: 'c.844C>T',
                polyphen_impact: 'probably_damaging',
                polyphen_score: 1,
                sift_impact: 'deleterious',
                sift_score: 0,
                vep_impact: 'MODERATE',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
          {
            consequence_id: '01e5e133-05dc-57f1-bf89-83553fe02547',
            transcript: {
              transcript_id: 'ENST00000620739',
              aa_change: 'R243W',
              is_canonical: false,
              consequence_type: 'missense_variant',
              annotation: {
                hgvsc: 'c.727C>T',
                polyphen_impact: 'probably_damaging',
                polyphen_score: 1,
                sift_impact: 'deleterious',
                sift_score: 0,
                vep_impact: 'MODERATE',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
          {
            consequence_id: 'cd00c554-0d4e-55ac-8d17-5155227c50f1',
            transcript: {
              transcript_id: 'ENST00000610292',
              aa_change: 'R243W',
              is_canonical: false,
              consequence_type: 'missense_variant',
              annotation: {
                hgvsc: 'c.727C>T',
                polyphen_impact: 'probably_damaging',
                polyphen_score: 1,
                sift_impact: 'deleterious',
                sift_score: 0,
                vep_impact: 'MODERATE',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
          {
            consequence_id: 'cf3682f6-e129-54b3-9a29-f50a3f213b44',
            transcript: {
              transcript_id: 'ENST00000604348',
              aa_change: null,
              is_canonical: false,
              consequence_type: 'downstream_gene_variant',
              annotation: {
                hgvsc: '',
                polyphen_impact: '',
                polyphen_score: null,
                sift_impact: '',
                sift_score: null,
                vep_impact: 'MODIFIER',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
          {
            consequence_id: '17b29f06-456f-5c01-ab60-d69f0a88151e',
            transcript: {
              transcript_id: 'ENST00000514944',
              aa_change: null,
              is_canonical: false,
              consequence_type: 'downstream_gene_variant',
              annotation: {
                hgvsc: '',
                polyphen_impact: '',
                polyphen_score: null,
                sift_impact: '',
                sift_score: null,
                vep_impact: 'MODIFIER',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
          {
            consequence_id: 'a5ad90b4-ad1a-5f3c-a5fc-e7c971b5143c',
            transcript: {
              transcript_id: 'ENST00000619485',
              aa_change: 'R243W',
              is_canonical: false,
              consequence_type: 'missense_variant',
              annotation: {
                hgvsc: 'c.727C>T',
                polyphen_impact: 'probably_damaging',
                polyphen_score: 1,
                sift_impact: 'deleterious',
                sift_score: 0,
                vep_impact: 'MODERATE',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
          {
            consequence_id: 'ffba87fb-ec68-5bae-8140-658a569e557f',
            transcript: {
              transcript_id: 'ENST00000509690',
              aa_change: 'R150W',
              is_canonical: false,
              consequence_type: 'missense_variant',
              annotation: {
                hgvsc: 'c.448C>T',
                polyphen_impact: 'probably_damaging',
                polyphen_score: 1,
                sift_impact: 'deleterious',
                sift_score: 0,
                vep_impact: 'MODERATE',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
          {
            consequence_id: '635d6143-964c-56fb-abe0-eac202c07fad',
            transcript: {
              transcript_id: 'ENST00000420246',
              aa_change: 'R282W',
              is_canonical: false,
              consequence_type: 'missense_variant',
              annotation: {
                hgvsc: 'c.844C>T',
                polyphen_impact: 'probably_damaging',
                polyphen_score: 0.999,
                sift_impact: 'deleterious',
                sift_score: 0,
                vep_impact: 'MODERATE',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
          {
            consequence_id: 'f2eeb31d-3e86-5bf4-8c45-50c8aeb06702',
            transcript: {
              transcript_id: 'ENST00000510385',
              aa_change: 'R150W',
              is_canonical: false,
              consequence_type: 'missense_variant',
              annotation: {
                hgvsc: 'c.448C>T',
                polyphen_impact: 'probably_damaging',
                polyphen_score: 0.999,
                sift_impact: 'deleterious',
                sift_score: 0,
                vep_impact: 'MODERATE',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
          {
            consequence_id: '4834df85-33d7-5a3b-bd64-a32de5df9bd4',
            transcript: {
              transcript_id: 'ENST00000269305',
              aa_change: 'R282W',
              is_canonical: true,
              consequence_type: 'missense_variant',
              annotation: {
                hgvsc: 'c.844C>T',
                polyphen_impact: 'probably_damaging',
                polyphen_score: 1,
                sift_impact: 'deleterious',
                sift_score: 0,
                vep_impact: 'MODERATE',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
          {
            consequence_id: 'ed36024c-ab8f-5189-8b95-6fa3b8333eb5',
            transcript: {
              transcript_id: 'ENST00000576024',
              aa_change: null,
              is_canonical: false,
              consequence_type: 'upstream_gene_variant',
              annotation: {
                hgvsc: '',
                polyphen_impact: '',
                polyphen_score: null,
                sift_impact: '',
                sift_score: null,
                vep_impact: 'MODIFIER',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
          {
            consequence_id: 'b9ce0f57-55c8-5fee-a398-e0d00e70b18b',
            transcript: {
              transcript_id: 'ENST00000413465',
              aa_change: null,
              is_canonical: false,
              consequence_type: 'intron_variant',
              annotation: {
                hgvsc: 'c.782+405C>T',
                polyphen_impact: '',
                polyphen_score: null,
                sift_impact: '',
                sift_score: null,
                vep_impact: 'MODIFIER',
              },
              gene: {
                gene_id: 'ENSG00000141510',
                symbol: 'TP53',
                gene_strand: -1,
              },
            },
          },
        ],
      },
    ],
  },
};
